print("Welcome to the bill calculator!")
total = float(input("What was the total bill? $"))
tip = int(input("What percentage tip would you like to give? (10, 12, or 15) "))
total = total * (1 + tip/100)
individual = int(input("How may people to split the bill? "))
final = "{:.2f}".format(total/individual)
print(f"Each person should pay: ${final}")
